# Deplacement PDF+Word vers l'archive - executer depuis la racine du depot
mkdir "docs\archive-accords-locaux\Format word" -ErrorAction SilentlyContinue

git mv "docs\accords-locaux\ACCORDS_Egalité femmes hommes_2023_Version signée.pdf" "docs\archive-accords-locaux\ACCORDS_Egalité femmes hommes_2023_Version signée.pdf"
git mv "docs\accords-locaux\Accords locaux Format word\Accord Egalité F H_V finale 2023-05-12.docx" "docs\archive-accords-locaux\Format word\Accord Egalité F H_V finale 2023-05-12.docx"
git mv "docs\accords-locaux\Accord égalité HF_Avenant signé.pdf" "docs\archive-accords-locaux\Accord égalité HF_Avenant signé.pdf"
git mv "docs\accords-locaux\Accords locaux Format word\Avenant accord égalité HF V finale.docx" "docs\archive-accords-locaux\Format word\Avenant accord égalité HF V finale.docx"
git mv "docs\accords-locaux\ACCORD INTERESSEMENT 2024_Version signée.pdf" "docs\archive-accords-locaux\ACCORD INTERESSEMENT 2024_Version signée.pdf"
git mv "docs\accords-locaux\Accords locaux Format word\Accord  interessement Vfinale.docx" "docs\archive-accords-locaux\Format word\Accord  interessement Vfinale.docx"
git mv "docs\accords-locaux\Accord intéressement 2025 - Version signée.pdf" "docs\archive-accords-locaux\Accord intéressement 2025 - Version signée.pdf"
git mv "docs\accords-locaux\Accords locaux Format word\Accord  interessement-Version finale.docx" "docs\archive-accords-locaux\Format word\Accord  interessement-Version finale.docx"
git mv "docs\accords-locaux\Avenant accord d'entreprise intergénérationnel_2023_Version signée.pdf" "docs\archive-accords-locaux\Avenant accord d'entreprise intergénérationnel_2023_Version signée.pdf"
git mv "docs\accords-locaux\Accords locaux Format word\Avenant Accord Intergénérationnel 2023.docx" "docs\archive-accords-locaux\Format word\Avenant Accord Intergénérationnel 2023.docx"
git mv "docs\accords-locaux\Accord sur le supplément d'intéressement au tire de l'exercice 2025 - Version signée.pdf" "docs\archive-accords-locaux\Accord sur le supplément d'intéressement au tire de l'exercice 2025 - Version signée.pdf"
git mv "docs\accords-locaux\Accords locaux Format word\Supplément d'intéressement.docx" "docs\archive-accords-locaux\Format word\Supplément d'intéressement.docx"
git mv "docs\elections\ACCORDS_Dialogue social_2023_Version signée.pdf" "docs\archive-accords-locaux\ACCORDS_Dialogue social_2023_Version signée.pdf"
git mv "docs\elections\Election Format WOrd\Accord sur le dialogue social 2023 _Version finale.docx" "docs\archive-accords-locaux\Format word\Accord sur le dialogue social 2023 _Version finale.docx"
git mv "docs\nao\NAO 2024 - PV Désaccord.pdf" "docs\archive-accords-locaux\NAO 2024 - PV Désaccord.pdf"
git mv "docs\nao\NAO Format Word\PV NAO 2024 - V Finale.docx" "docs\archive-accords-locaux\Format word\PV NAO 2024 - V Finale.docx"
git mv "docs\nao\NAO 2025 - Procès verbal de désaccord.pdf" "docs\archive-accords-locaux\NAO 2025 - Procès verbal de désaccord.pdf"
git mv "docs\nao\NAO Format Word\PV NAO 2025 - V 2.docx" "docs\archive-accords-locaux\Format word\PV NAO 2025 - V 2.docx"
git mv "docs\accords-locaux\Accords locaux Format word\Accord Intergénérationnel_Avenant n°1_vDéfinitive.docx" "docs\archive-accords-locaux\Format word\Accord Intergénérationnel_Avenant n°1_vDéfinitive.docx"
git mv "docs\accords-locaux\Accords locaux Format word\Supplément d'intéressement 2023.docx" "docs\archive-accords-locaux\Format word\Supplément d'intéressement 2023.docx"
git mv "docs\elections\Election Format WOrd\Accord Vote électronique_v2022-09-23.docx" "docs\archive-accords-locaux\Format word\Accord Vote électronique_v2022-09-23.docx"
git mv "docs\nao\NAO Format Word\Accord de méthode NAO 2024_vfinale.docx" "docs\archive-accords-locaux\Format word\Accord de méthode NAO 2024_vfinale.docx"
git mv "docs\nao\NAO Format Word\Accord de méthode NAO 2025.docx" "docs\archive-accords-locaux\Format word\Accord de méthode NAO 2025.docx"
git mv "docs\nao\NAO 2026 _PV de désaccord signé.pdf" "docs\archive-accords-locaux\NAO 2026 _PV de désaccord signé.pdf"