#!/bin/bash
# A lancer depuis la racine du depot fo-ico-documents
set -e

git mv "docs/archive-accords-locaux/ACCORD INTERESSEMENT 2024_Version signee.md" "docs/archive-accords-locaux/ACCORD INTERESSEMENT 2024_Version signee plus en vigueur.md"
git mv "docs/archive-accords-locaux/ACCORD INTERESSEMENT 2024_Version signée.pdf" "docs/archive-accords-locaux/ACCORD INTERESSEMENT 2024_Version signée plus en vigueur.pdf"
git mv "docs/archive-accords-locaux/ACCORDS_Dialogue social_2023_Version signee.md" "docs/archive-accords-locaux/ACCORDS_Dialogue social_2023_Version signee plus en vigueur.md"
git mv "docs/archive-accords-locaux/ACCORDS_Dialogue social_2023_Version signée.pdf" "docs/archive-accords-locaux/ACCORDS_Dialogue social_2023_Version signée plus en vigueur.pdf"
git mv "docs/archive-accords-locaux/ACCORDS_Egalite femmes hommes_2023_Version signee.md" "docs/archive-accords-locaux/ACCORDS_Egalite femmes hommes_2023_Version signee plus en vigueur.md"
git mv "docs/archive-accords-locaux/ACCORDS_Egalité femmes hommes_2023_Version signée.pdf" "docs/archive-accords-locaux/ACCORDS_Egalité femmes hommes_2023_Version signée plus en vigueur.pdf"
git mv "docs/archive-accords-locaux/Accord egalite HF_Avenant signe.md" "docs/archive-accords-locaux/Accord egalite HF_Avenant signe plus en vigueur.md"
git mv "docs/archive-accords-locaux/Accord interessement 2025 - Version signee.md" "docs/archive-accords-locaux/Accord interessement 2025 - Version signee plus en vigueur.md"
git mv "docs/archive-accords-locaux/Accord intéressement 2025 - Version signée.pdf" "docs/archive-accords-locaux/Accord intéressement 2025 - Version signée plus en vigueur.pdf"
git mv "docs/archive-accords-locaux/Accord preparatoire PAPE 2022_Signe.pdf" "docs/archive-accords-locaux/Accord preparatoire PAPE 2022_Signe plus en vigueur.pdf"
git mv "docs/archive-accords-locaux/Accord sur le supplement d'interessement au tire de l'exercice 2025 - Version signee.md" "docs/archive-accords-locaux/Accord sur le supplement d'interessement au tire de l'exercice 2025 - Version signee plus en vigueur.md"
git mv "docs/archive-accords-locaux/Accord sur le supplément d'intéressement au tire de l'exercice 2025 - Version signée.pdf" "docs/archive-accords-locaux/Accord sur le supplément d'intéressement au tire de l'exercice 2025 - Version signée plus en vigueur.pdf"
git mv "docs/archive-accords-locaux/Accord égalité HF_Avenant signé.pdf" "docs/archive-accords-locaux/Accord égalité HF_Avenant signé plus en vigueur.pdf"
git mv "docs/archive-accords-locaux/Avenant accord d'entreprise intergénérationnel_2023_Version signée.pdf" "docs/archive-accords-locaux/Avenant accord d'entreprise intergénérationnel_2023_Version signée plus en vigueur.pdf"
git mv "docs/archive-accords-locaux/Format word/Accord  interessement Vfinale.docx" "docs/archive-accords-locaux/Format word/Accord  interessement Vfinale plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/Accord  interessement-Version finale.docx" "docs/archive-accords-locaux/Format word/Accord  interessement-Version finale plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/Accord Egalité F H_V finale 2023-05-12.docx" "docs/archive-accords-locaux/Format word/Accord Egalité F H_V finale 2023-05-12 plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/Accord Intergénérationnel_Avenant n°1_vDéfinitive.docx" "docs/archive-accords-locaux/Format word/Accord Intergénérationnel_Avenant n°1_vDéfinitive plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/Accord Vote électronique_v2022-09-23.docx" "docs/archive-accords-locaux/Format word/Accord Vote électronique_v2022-09-23 plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/Accord de méthode NAO 2024_vfinale.docx" "docs/archive-accords-locaux/Format word/Accord de méthode NAO 2024_vfinale plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/Accord de méthode NAO 2025.docx" "docs/archive-accords-locaux/Format word/Accord de méthode NAO 2025 plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/Accord sur le dialogue social 2023 _Version finale.docx" "docs/archive-accords-locaux/Format word/Accord sur le dialogue social 2023 _Version finale plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/Avenant Accord Intergénérationnel 2023.docx" "docs/archive-accords-locaux/Format word/Avenant Accord Intergénérationnel 2023 plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/Avenant accord égalité HF V finale.docx" "docs/archive-accords-locaux/Format word/Avenant accord égalité HF V finale plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/PV NAO 2024 - V Finale.docx" "docs/archive-accords-locaux/Format word/PV NAO 2024 - V Finale plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/PV NAO 2025 - V 2.docx" "docs/archive-accords-locaux/Format word/PV NAO 2025 - V 2 plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/Supplément d'intéressement 2023.docx" "docs/archive-accords-locaux/Format word/Supplément d'intéressement 2023 plus en vigueur.docx"
git mv "docs/archive-accords-locaux/Format word/Supplément d'intéressement.docx" "docs/archive-accords-locaux/Format word/Supplément d'intéressement plus en vigueur.docx"
git mv "docs/archive-accords-locaux/accord-financement-syndical-2021.md" "docs/archive-accords-locaux/accord-financement-syndical-2021 plus en vigueur.md"
git mv "docs/archive-accords-locaux/accord-methode-nao-2024.md" "docs/archive-accords-locaux/accord-methode-nao-2024 plus en vigueur.md"
git mv "docs/archive-accords-locaux/accord-methode-nao-2025.md" "docs/archive-accords-locaux/accord-methode-nao-2025 plus en vigueur.md"
git mv "docs/archive-accords-locaux/accord-supplement-interessement-2023.md" "docs/archive-accords-locaux/accord-supplement-interessement-2023 plus en vigueur.md"
git mv "docs/archive-accords-locaux/accord-vote-electronique-2022.md" "docs/archive-accords-locaux/accord-vote-electronique-2022 plus en vigueur.md"

git commit -m "Archive : ajout de \"plus en vigueur\" a 33 noms de fichiers"
git push
